# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20171114_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
