# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='webmail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
