# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20171114_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='publ',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
    ]
