# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20171115_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publications',
            new_name='publication',
        ),
    ]
