# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20171115_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
    ]
