# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_project_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContMTstudents',
            new_name='completeBTstudents',
        ),
        migrations.RenameModel(
            old_name='ContBTstudents',
            new_name='completeMTstudents',
        ),
        migrations.RenameModel(
            old_name='CompPhdstudents',
            new_name='completePHDstudents',
        ),
        migrations.RenameModel(
            old_name='ContPhdstudents',
            new_name='continiuingBTstudents',
        ),
        migrations.RenameModel(
            old_name='CompBTstudents',
            new_name='continuingMTstudents',
        ),
        migrations.RenameModel(
            old_name='CompMTstudents',
            new_name='continuingPHDstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cmt',
            new_name='completeBTstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cbt',
            new_name='completeMTstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cophd',
            new_name='completePHDstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cphd',
            new_name='continiuingBTstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cobt',
            new_name='continuingMTstudents',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='comt',
            new_name='continuingPHDstudents',
        ),
    ]
