# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20171115_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='completebtstudents',
            name='completeBTstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
        migrations.AddField(
            model_name='completemtstudents',
            name='completeMTstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
        migrations.AddField(
            model_name='completephdstudents',
            name='completePHDstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
        migrations.AddField(
            model_name='continiuingbtstudents',
            name='continiuingBTstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
        migrations.AddField(
            model_name='continuingmtstudents',
            name='continuingMTstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
        migrations.AddField(
            model_name='continuingphdstudents',
            name='continuingPHDstudents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info'),
        ),
    ]
