# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20171115_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='completeBTstudents',
        ),
        migrations.RemoveField(
            model_name='students',
            name='completeMTstudents',
        ),
        migrations.RemoveField(
            model_name='students',
            name='completePHDstudents',
        ),
        migrations.RemoveField(
            model_name='students',
            name='continiuingBTstudents',
        ),
        migrations.RemoveField(
            model_name='students',
            name='continuingMTstudents',
        ),
        migrations.RemoveField(
            model_name='students',
            name='continuingPHDstudents',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
