# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20171115_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completemtstudents',
            old_name='completeMTstudents',
            new_name='completemtstudents',
        ),
        migrations.RenameField(
            model_name='completephdstudents',
            old_name='completePHDstudents',
            new_name='completephdstudents',
        ),
        migrations.RenameField(
            model_name='continuingbtstudents',
            old_name='continuingBTstudents',
            new_name='continuingbtstudents',
        ),
        migrations.RenameField(
            model_name='continuingmtstudents',
            old_name='continuingMTstudents',
            new_name='continuingmtstudents',
        ),
        migrations.RenameField(
            model_name='continuingphdstudents',
            old_name='continuingPHDstudents',
            new_name='continuingphdstudents',
        ),
    ]
