# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20171115_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('sem', models.CharField(choices=[('odd', 'odd'), ('even', 'even')], default='odd', max_length=4)),
                ('course', models.CharField(max_length=500)),
                ('teaching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Info')),
            ],
        ),
    ]
