# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20171122_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startyear',
            field=models.IntegerField(),
        ),
    ]
